#!/bin/sh

# set -x

DOCKER=`which docker`

if [ $? -ne 0 ]; then
  echo "ERROR: Cannot fine Docker, please visit https://docs.docker.com/engine/installation" >&2
  exit 1
fi

SUDO=`which sudo`

if [ $? -ne 0 ]; then
  echo "ERROR: Cannot find sudo" >&2
  exit 1
fi

CURL=`which curl`

if [ $? -ne 0 ]; then
  WGET=`which wget`

  if [ $? -ne 0 ]; then
    echo "ERROR: Cannot find curl or wget" >&2
    exit 1
  fi
fi

INSTALLDIR=/usr/local

sudo -- sh -c "if [ ! -d /usr/local ] || [ ! -w /usr/local ]; then exit 1; fi"

if [ $? -ne 0 ]; then
  sudo -- sh -c "if [ ! -d /opt ] || [ ! -w /opt ]; then exit 1; fi"

  if [ $? -ne 0 ]; then
    echo "ERROR: Cannot write to /usr/local or /opt"
    exit 1
  fi

  INSTALLDIR=/opt
fi

DOCKER_COMPOSE=`which docker-compose`

if [ $? -ne 0 ] && [ ! -f $INSTALLDIR/bin/docker-compose ]; then
  echo "Docker Compose does not exist, getting it"

  sudo mkdir -p $INSTALLDIR/bin

  DOCKER_COMPOSE=$INSTALLDIR/bin/docker-compose

  if [ ! -z $CURL ]; then
    $CURL -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m` | sudo tee $DOCKER_COMPOSE > /dev/null
  else
    $WGET -O - https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m` | sudo tee $DOCKER_COMPOSE > /dev/null
  fi

  sudo chmod +x $DOCKER_COMPOSE
fi

# clone the repo to $INSTALLDIR/docker-uptime
if [ ! -d $INSTALLDIR/docker-uptime ]; then
  echo "Cloning https://github.com/IFSight/uptime.git"

  # seen some issues of minimal distros not being able to validate github cert
  sudo GIT_SSL_NO_VERIFY=true git clone https://github.com/IFSight/uptime.git $INSTALLDIR/docker-uptime
else
  echo "Updating from https://github.com/IFSight/uptime.git"

  cd $INSTALLDIR/docker-uptime

  sudo git pull

  echo "Stopping and removing containers if they exist, then pulling"
  sudo -- sh -c "INSTALLDIR=$INSTALLDIR $DOCKER_COMPOSE --file $INSTALLDIR/docker-uptime/compose/uptime.yml stop"
  sudo -- sh -c "INSTALLDIR=$INSTALLDIR $DOCKER_COMPOSE --file $INSTALLDIR/docker-uptime/compose/uptime.yml rm -f"
  sudo -- sh -c "INSTALLDIR=$INSTALLDIR $DOCKER_COMPOSE --file $INSTALLDIR/docker-uptime/compose/uptime.yml pull"
fi

echo "Starting everything up"
sudo -- sh -c "INSTALLDIR=$INSTALLDIR $DOCKER_COMPOSE --file $INSTALLDIR/docker-uptime/compose/uptime.yml up -d"

sudo -- sh -c "INSTALLDIR=$INSTALLDIR $DOCKER_COMPOSE --file $INSTALLDIR/docker-uptime/compose/uptime.yml ps"

if [ ! -z $CURL ]; then
  MYIP=$(curl -s -L raw.ip.ifsight.net)
else
  MYIP=$(wget -q -O - raw.ip.ifsight.net)
fi

echo "To see uptime web interface, visit http://$MYIP:8082/"
